<?php
// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Fralenuvole
 * class-dashboard.php - Dashboard widgets and functionality
 */

/**
 * Dashboard Class
 * Handles rendering of dashboard widgets and related functionality
 */
class Frl_Admin_Dashboard {

	/**
	 * Constructor.
	 *
	 * @return void
	 */
	public function __construct() {
		// No initialization needed
	}

	/**
	 * Render the dashboard overview widget
	 *
	 * This method renders the overview widget by assembling sections
	 * generated by the respective display classes.
	 *
	 * @param string $content Optional additional content.
	 * @return string HTML content.
	 */
	public function render( $content = '' ) {
		// Instantiate the display classes
		$cache_display = new Frl_Cache_Display();
		$env_display   = new Frl_Environment_Display();

		// Get the environment data, as it's needed by both sections
		$env_data = frl_environment_display_get_stats();

		// --- Render sections from display classes ---
		$env_widget   = $env_display->render_dashboard_widget( $env_data );
		$cache_widget = $cache_display->render_dashboard_widget( $env_data );

		// Use the flexible layout renderer for a 2-column layout with only the main content
		$columns = frl_ui_render_flex_layout(
			array( $env_widget['main'], $cache_widget['main'] ),
			2,
			'dashboard-stats'
		);

		// Build the complete widget content, appending hidden sections after the columns
		$widget_content = frl_ui_render_widget(
			'dashboard-overview',
			$columns . $env_widget['hidden'] . $cache_widget['hidden'],
			'Environment & Cache',
		);

		$widget_content .= frl_ui_render_widget(
			'tag-validator-overview',
			frl_tag_validator_render(),
			'',
			'tag-validator-overview',
			0,
			true
		);

		$widget_content .= frl_ui_render_widget(
			'environment-overview',
			frl_environment_display_render(),
		);

		$widget_content .= frl_ui_render_widget(
			'plugins-exclusions-overview',
			$this->render_plugins_exclusions_widget(),
			'Third-Party Plugins Exclusions',
			'plugins-exclusions-overview',
			0,
			true
		);

		$widget_content .= frl_ui_render_widget(
			'widget-admin-actions',
			frl_render_clear_cache_buttons() . frl_render_admin_actions_buttons(),
		);

		// Add any additional content
		if ( ! empty( $content ) ) {
			$widget_content .= frl_ui_render_widget(
				'additional-content',
				$content,
			);
		}

		// Render the final widget
		return $widget_content;
	}

	/**
	 * Render the plugin exclusions widget.
	 *
	 * @return string HTML content.
	 */
	public function render_plugins_exclusions_widget() {
		$env_display = new Frl_Environment_Display();
		return $env_display->get_plugins_exclusions_status();
	}
}
